export const Navlinks = [
  { label: "Browse", path: "/browse" },
  { label: "Search", path: "/search" },
  { label: "Profile", path: "/profile" },
  { label: "Help", path: "/help" },
  // {label:'Browse',
  //     path:'/browse'
  // },
];
export const Footerlinks = [
  {
    title: "Company",
    links: [
      { label: "About", path: "" },
      { label: "How it works", path: "" },
      { label: "Coperation", path: "" },
    ],
  },
  {
    title: "Support",
    links: [
      { label: "Community", path: "" },
      { label: "Livechat", path: "" },
      { label: "FAQ", path: "" },
    ],
  },
  {
    title: "Links",
    links: [
      { label: "Help & Support", path: "" },
      { label: "Terms & Privacy", path: "" },
      { label: "Cookies", path: "" },
    ],
  },
  {
    title: "Location",
    links: [
      { label: "Kwabenya - Pokuasi RD", path: "" },
      { label: "Ghana, Greater - Accra", path: "" },
    ],
  },
  {
    title: "Connect",
    links: [
      { label: "info@logo.com", path: "" },
      { label: "(233) 248 503 913", path: "" },
    ],
  },
];

export const Cars = [
  {
    brand: "Audi",
    category: "Sedan",
    Carname: "RS7",
    production_year: "2023",
    condition: "New",
    price: "Ghc 500,000",
    mileage: "0",
    reviews: "55",
    description:
      "The Audi RS7 is a high-performance version of the A7 luxury sedan. It comes with a 591-horsepower V8 engine, a sport-tuned suspension, and a host of performance upgrades. The RS7 is a great choice for drivers who want a luxury car that can also deliver thrilling performance.",
    specs: {
      engine: "4.0L V8",
      horsepower: "591",
      torque: "590 lb-ft",
      acceleration: "3.5 sec",
      top_speed: "190 mph",
      fuel_economy: "15/22 mpg",
      drive_type: "AWD",
      seating: "5",
      cargo_space: "24.6 cu ft",
      warranty: "4 yr/50,000 mi",
      transmission: "8-speed automatic",
      infotainment_system: "MMI Navigation plus with MMI touch response",
      safety_features: [
        "Adaptive Cruise Control",
        "Lane Departure Warning",
        "Blind Spot Monitoring",
      ],
      color_options: ["Nardo Gray", "Mythos Black", "Tango Red"],
    },
    images: {
      interior_images: {
        dashboard: "url_to_dashboard_image",
        seats: "url_to_seats_image",
      },
      exterior_images: {
        front_view: "url_to_front_view_image",
        rear_view: "url_to_rear_view_image",
      },
    },
    dealer_info: {
      name: "Audi Center Accra",
      address: "123 Luxury Ave, Accra, Ghana",
      contact: "030 123 4567",
      email: "sales@audicenteraccra.com",
    },
  },
  {
    brand: "BMW",
    category: "SUV",
    Carname: "X5 M",
    production_year: "2023",
    condition: "New",
    price: "Ghc 600,000",
    mileage: "0",
    reviews: "45",
    description:
      "The BMW X5 M is a high-performance SUV that combines luxury with power. It features a 4.4-liter V8 engine, delivering 617 horsepower and a dynamic driving experience. The X5 M is perfect for those who need the practicality of an SUV but crave the thrill of a sports car.",
    specs: {
      engine: "4.4L V8",
      horsepower: "617",
      torque: "553 lb-ft",
      acceleration: "3.8 sec",
      top_speed: "177 mph",
      fuel_economy: "13/18 mpg",
      drive_type: "AWD",
      seating: "5",
      cargo_space: "33.9 cu ft",
      warranty: "4 yr/50,000 mi",
      transmission: "8-speed automatic",
      infotainment_system: "iDrive 7.0 with 12.3-inch display",
      safety_features: [
        "Adaptive Cruise Control",
        "Lane Keeping Assist",
        "Blind Spot Detection",
      ],
      color_options: ["Alpine White", "Carbon Black", "Marina Bay Blue"],
    },
    images: {
      interior_images: {
        dashboard: "url_to_dashboard_image",
        seats: "url_to_seats_image",
      },
      exterior_images: {
        front_view: "url_to_front_view_image",
        rear_view: "url_to_rear_view_image",
      },
    },
    dealer_info: {
      name: "BMW Center Accra",
      address: "456 Prestige Blvd, Accra, Ghana",
      contact: "030 987 6543",
      email: "sales@bmwcenteraccra.com",
    },
  },
  {
    brand: "Mercedes-Benz",
    category: "Coupe",
    Carname: "AMG GT",
    production_year: "2023",
    condition: "New",
    price: "Ghc 700,000",
    mileage: "0",
    reviews: "60",
    description:
      "The Mercedes-Benz AMG GT is a luxury sports coupe with a powerful 4.0-liter V8 engine. It offers a thrilling driving experience with its 577 horsepower and advanced performance features. The AMG GT is designed for those who appreciate both luxury and speed.",
    specs: {
      engine: "4.0L V8",
      horsepower: "577",
      torque: "516 lb-ft",
      acceleration: "3.7 sec",
      top_speed: "193 mph",
      fuel_economy: "16/22 mpg",
      drive_type: "RWD",
      seating: "2",
      cargo_space: "10.1 cu ft",
      warranty: "4 yr/50,000 mi",
      transmission: "7-speed dual-clutch automatic",
      infotainment_system: "COMAND system with 10.25-inch display",
      safety_features: [
        "Active Brake Assist",
        "Attention Assist",
        "Blind Spot Assist",
      ],
      color_options: [
        "Designo Selenite Grey",
        "Obsidian Black",
        "Brilliant Blue",
      ],
    },
    images: {
      interior_images: {
        dashboard: "url_to_dashboard_image",
        seats: "url_to_seats_image",
      },
      exterior_images: {
        front_view: "url_to_front_view_image",
        rear_view: "url_to_rear_view_image",
      },
    },
    dealer_info: {
      name: "Mercedes-Benz Center Accra",
      address: "789 Elite St, Accra, Ghana",
      contact: "030 654 3210",
      email: "sales@mercedescenteraccra.com",
    },
  },
  {
    Brand: "Audi",
    category: "Sedan",
    Carname: "RS7",
    production_year: "2023",
    condition: "New",
    price: "Ghc 500,000",
    mileage: "0",
    reviews: "55",
    description:
      "The Audi RS7 is a high-performance version of the A7 luxury sedan. It comes with a 591-horsepower V8 engine, a sport-tuned suspension, and a host of performance upgrades. The RS7 is a great choice for drivers who want a luxury car that can also deliver thrilling performance.",
    specs: {
      engine: "4.0L V8",
      horsepower: "591",
      torque: "590 lb-ft",
      acceleration: "3.5 sec",
      top_speed: "190 mph",
      fuel_economy: "15/22 mpg",
      drive_type: "AWD",
      seating: "5",
      cargo_space: "24.6 cu ft",
      warranty: "4 yr/50,000 mi",
      transmission: "8-speed automatic",
      infotainment_system: "MMI Navigation plus with MMI touch response",
      safety_features: [
        "Adaptive Cruise Control",
        "Lane Departure Warning",
        "Blind Spot Monitoring",
      ],
      color_options: ["Nardo Gray", "Mythos Black", "Tango Red"],
    },
    images: {
      interior_images: {
        dashboard: "url_to_dashboard_image",
        seats: "url_to_seats_image",
      },
      exterior_images: {
        front_view: "url_to_front_view_image",
        rear_view: "url_to_rear_view_image",
      },
    },
    dealer_info: {
      name: "Audi Center Accra",
      address: "123 Luxury Ave, Accra, Ghana",
      contact: "030 123 4567",
      email: "sales@audicenteraccra.com",
    },
  },
  {
    Brand: "BMW",
    category: "SUV",
    Carname: "X5 M",
    production_year: "2023",
    condition: "New",
    price: "Ghc 600,000",
    mileage: "0",
    reviews: "45",
    description:
      "The BMW X5 M is a high-performance SUV that combines luxury with power. It features a 4.4-liter V8 engine, delivering 617 horsepower and a dynamic driving experience. The X5 M is perfect for those who need the practicality of an SUV but crave the thrill of a sports car.",
    specs: {
      engine: "4.4L V8",
      horsepower: "617",
      torque: "553 lb-ft",
      acceleration: "3.8 sec",
      top_speed: "177 mph",
      fuel_economy: "13/18 mpg",
      drive_type: "AWD",
      seating: "5",
      cargo_space: "33.9 cu ft",
      warranty: "4 yr/50,000 mi",
      transmission: "8-speed automatic",
      infotainment_system: "iDrive 7.0 with 12.3-inch display",
      safety_features: [
        "Adaptive Cruise Control",
        "Lane Keeping Assist",
        "Blind Spot Detection",
      ],
      color_options: ["Alpine White", "Carbon Black", "Marina Bay Blue"],
    },
    images: {
      interior_images: {
        dashboard: "url_to_dashboard_image",
        seats: "url_to_seats_image",
      },
      exterior_images: {
        front_view: "url_to_front_view_image",
        rear_view: "url_to_rear_view_image",
      },
    },
    dealer_info: {
      name: "BMW Center Accra",
      address: "456 Prestige Blvd, Accra, Ghana",
      contact: "030 987 6543",
      email: "sales@bmwcenteraccra.com",
    },
  },
  {
    Brand: "Mercedes-Benz",
    category: "Coupe",
    Carname: "AMG GT",
    production_year: "2023",
    condition: "New",
    price: "Ghc 700,000",
    mileage: "0",
    reviews: "60",
    description:
      "The Mercedes-Benz AMG GT is a luxury sports coupe with a powerful 4.0-liter V8 engine. It offers a thrilling driving experience with its 577 horsepower and advanced performance features. The AMG GT is designed for those who appreciate both luxury and speed.",
    specs: {
      engine: "4.0L V8",
      horsepower: "577",
      torque: "516 lb-ft",
      acceleration: "3.7 sec",
      top_speed: "193 mph",
      fuel_economy: "16/22 mpg",
      drive_type: "RWD",
      seating: "2",
      cargo_space: "10.1 cu ft",
      warranty: "4 yr/50,000 mi",
      transmission: "7-speed dual-clutch automatic",
      infotainment_system: "COMAND system with 10.25-inch display",
      safety_features: [
        "Active Brake Assist",
        "Attention Assist",
        "Blind Spot Assist",
      ],
      color_options: [
        "Designo Selenite Grey",
        "Obsidian Black",
        "Brilliant Blue",
      ],
    },
    images: {
      interior_images: {
        dashboard: "url_to_dashboard_image",
        seats: "url_to_seats_image",
      },
      exterior_images: {
        front_view: "url_to_front_view_image",
        rear_view: "url_to_rear_view_image",
      },
    },
    dealer_info: {
      name: "Mercedes-Benz Center Accra",
      address: "789 Elite St, Accra, Ghana",
      contact: "030 654 3210",
      email: "sales@mercedescenteraccra.com",
    },
  },

  {
    Brand: "Tesla",
    category: "Sedan",
    Carname: "Model S Plaid",
    production_year: "2023",
    condition: "New",
    price: "Ghc 800,000",
    mileage: "0",
    reviews: "70",
    description:
      "The Tesla Model S Plaid is an all-electric luxury sedan with incredible performance. It features a tri-motor setup producing over 1,000 horsepower, allowing it to accelerate from 0 to 60 mph in under 2 seconds. The Model S Plaid also offers advanced autonomous driving features and a long electric range.",
    specs: {
      engine: "Electric",
      horsepower: "1,020",
      torque: "1,050 lb-ft",
      acceleration: "1.99 sec",
      top_speed: "200 mph",
      fuel_economy: "120 MPGe",
      drive_type: "AWD",
      seating: "5",
      cargo_space: "28 cu ft",
      warranty: "4 yr/50,000 mi",
      transmission: "Single-speed",
      infotainment_system: "17-inch touchscreen with Tesla software",
      safety_features: [
        "Autopilot",
        "Full Self-Driving Capability",
        "Collision Avoidance",
      ],
      color_options: ["Pearl White", "Solid Black", "Red Multi-Coat"],
    },
    images: {
      interior_images: {
        dashboard: "url_to_dashboard_image",
        seats: "url_to_seats_image",
      },
      exterior_images: {
        front_view: "url_to_front_view_image",
        rear_view: "url_to_rear_view_image",
      },
    },
    dealer_info: {
      name: "Tesla Center Accra",
      address: "101 Electric Ave, Accra, Ghana",
      contact: "030 111 2222",
      email: "sales@teslacenteraccra.com",
    },
  },
  {
    Brand: "Porsche",
    category: "SUV",
    Carname: "Cayenne Turbo",
    production_year: "2023",
    condition: "New",
    price: "Ghc 750,000",
    mileage: "0",
    reviews: "50",
    description:
      "The Porsche Cayenne Turbo is a high-performance luxury SUV with a powerful 4.0-liter V8 engine. It delivers 541 horsepower and offers a dynamic driving experience with advanced handling and comfort features. The Cayenne Turbo is perfect for those who want a sporty SUV with premium amenities.",
    specs: {
      engine: "4.0L V8",
      horsepower: "541",
      torque: "567 lb-ft",
      acceleration: "3.9 sec",
      top_speed: "177 mph",
      fuel_economy: "15/19 mpg",
      drive_type: "AWD",
      seating: "5",
      cargo_space: "27.1 cu ft",
      warranty: "4 yr/50,000 mi",
      transmission: "8-speed automatic",
      infotainment_system:
        "Porsche Communication Management with 12.3-inch display",
      safety_features: [
        "Adaptive Cruise Control",
        "Lane Change Assist",
        "ParkAssist",
      ],
      color_options: [
        "Jet Black Metallic",
        "Carrara White Metallic",
        "Quartzite Grey Metallic",
      ],
    },
    images: {
      interior_images: {
        dashboard: "url_to_dashboard_image",
        seats: "url_to_seats_image",
      },
      exterior_images: {
        front_view: "url_to_front_view_image",
        rear_view: "url_to_rear_view_image",
      },
    },
    dealer_info: {
      name: "Porsche Center Accra",
      address: "202 Performance Blvd, Accra, Ghana",
      contact: "030 333 4444",
      email: "sales@porschecenteraccra.com",
    },
  },
  {
    Brand: "Lexus",
    category: "Sedan",
    Carname: "LS 500",
    production_year: "2023",
    condition: "New",
    price: "Ghc 550,000",
    mileage: "0",
    reviews: "40",
    description:
      "The Lexus LS 500 is a flagship luxury sedan that offers a smooth and refined driving experience. It features a 3.5-liter V6 engine with twin-turbochargers, producing 416 horsepower. The LS 500 is known for its luxurious interior, advanced technology, and exceptional build quality.",
    specs: {
      engine: "3.5L V6",
      horsepower: "416",
      torque: "442 lb-ft",
      acceleration: "4.6 sec",
      top_speed: "155 mph",
      fuel_economy: "19/30 mpg",
      drive_type: "RWD",
      seating: "5",
      cargo_space: "16.95 cu ft",
      warranty: "4 yr/50,000 mi",
      transmission: "10-speed automatic",
      infotainment_system: "12.3-inch touchscreen with Lexus Enform",
      safety_features: [
        "Pre-Collision System",
        "Lane Departure Alert",
        "Dynamic Radar Cruise Control",
      ],
      color_options: ["Eminent White Pearl", "Obsidian", "Matador Red Mica"],
    },
    images: {
      interior_images: {
        dashboard: "url_to_dashboard_image",
        seats: "url_to_seats_image",
      },
      exterior_images: {
        front_view: "url_to_front_view_image",
        rear_view: "url_to_rear_view_image",
      },
    },
    dealer_info: {
      name: "Lexus Center Accra",
      address: "303 Luxury Lane, Accra, Ghana",
      contact: "030 555 6666",
      email: "sales@lexuscenteraccra.com",
    },
  },
  {
    Brand: "Jaguar",
    category: "SUV",
    Carname: "F-Pace SVR",
    production_year: "2023",
    condition: "New",
    price: "Ghc 650,000",
    mileage: "0",
    reviews: "35",
    description:
      "The Jaguar F-Pace SVR is a high-performance SUV that combines luxury with thrilling performance. It features a 5.0-liter supercharged V8 engine, delivering 550 horsepower. The F-Pace SVR offers a dynamic driving experience with its sport-tuned suspension and advanced technology.",
    specs: {
      engine: "5.0L V8",
      horsepower: "550",
      torque: "502 lb-ft",
      acceleration: "4.1 sec",
      top_speed: "176 mph",
      fuel_economy: "16/21 mpg",
      drive_type: "AWD",
      seating: "5",
      cargo_space: "31.5 cu ft",
      warranty: "5 yr/60,000 mi",
      transmission: "8-speed automatic",
      infotainment_system: "Pivi Pro with 11.4-inch touchscreen",
      safety_features: [
        "Adaptive Cruise Control",
        "Blind Spot Assist",
        "Driver Condition Monitor",
      ],
      color_options: ["Santorini Black", "Eiger Grey", "Firenze Red"],
    },
    images: {
      interior_images: {
        dashboard: "url_to_dashboard_image",
        seats: "url_to_seats_image",
      },
      exterior_images: {
        front_view: "url_to_front_view_image",
        rear_view: "url_to_rear_view_image",
      },
    },
    dealer_info: {
      name: "Jaguar Center Accra",
      address: "404 Prestige Drive, Accra, Ghana",
      contact: "030 777 8888",
      email: "sales@jaguarcenteraccra.com",
    },
  },
  {
    Brand: "Land Rover",
    category: "SUV",
    Carname: "Range Rover Sport",
    production_year: "2023",
    condition: "New",
    price: "Ghc 700,000",
    mileage: "0",
    reviews: "50",
    description:
      "The Land Rover Range Rover Sport is a luxury SUV known for its off-road capability and refined interior. It features a 3.0-liter inline-six engine with mild hybrid technology, producing 395 horsepower. The Range Rover Sport offers a perfect blend of performance, luxury, and versatility.",
    specs: {
      engine: "3.0L I6",
      horsepower: "395",
      torque: "406 lb-ft",
      acceleration: "5.9 sec",
      top_speed: "140 mph",
      fuel_economy: "19/24 mpg",
      drive_type: "AWD",
      seating: "5",
      cargo_space: "27.5 cu ft",
      warranty: "4 yr/50,000 mi",
      transmission: "8-speed automatic",
      infotainment_system: "Pivi Pro with 10-inch touchscreen",
      safety_features: [
        "Adaptive Cruise Control",
        "Lane Keep Assist",
        "360-degree Camera",
      ],
      color_options: ["Fuji White", "Santorini Black", "Portofino Blue"],
    },
    images: {
      interior_images: {
        dashboard: "url_to_dashboard_image",
        seats: "url_to_seats_image",
      },
      exterior_images: {
        front_view: "url_to_front_view_image",
        rear_view: "url_to_rear_view_image",
      },
    },
    dealer_info: {
      name: "Land Rover Center Accra",
      address: "505 Adventure Road, Accra, Ghana",
      contact: "030 999 0000",
      email: "sales@landrovercenteraccra.com",
    },
  },
  {
    Brand: "Volvo",
    category: "SUV",
    Carname: "XC90",
    production_year: "2023",
    condition: "New",
    price: "Ghc 550,000",
    mileage: "0",
    reviews: "40",
    description:
      "The Volvo XC90 is a luxury SUV known for its safety features and Scandinavian design. It features a 2.0-liter four-cylinder engine with both turbocharging and supercharging, producing 316 horsepower. The XC90 offers a spacious and elegant interior with advanced technology.",
    specs: {
      engine: "2.0L I4",
      horsepower: "316",
      torque: "295 lb-ft",
      acceleration: "6.1 sec",
      top_speed: "130 mph",
      fuel_economy: "21/30 mpg",
      drive_type: "AWD",
      seating: "7",
      cargo_space: "15.8 cu ft",
      warranty: "4 yr/50,000 mi",
      transmission: "8-speed automatic",
      infotainment_system: "Sensus Connect with 9-inch touchscreen",
      safety_features: [
        "City Safety",
        "Pilot Assist",
        "Run-off Road Protection",
      ],
      color_options: ["Crystal White", "Onyx Black", "Denim Blue"],
    },
    images: {
      interior_images: {
        dashboard: "url_to_dashboard_image",
        seats: "url_to_seats_image",
      },
      exterior_images: {
        front_view: "url_to_front_view_image",
        rear_view: "url_to_rear_view_image",
      },
    },
    dealer_info: {
      name: "Volvo Center Accra",
      address: "606 Safety St, Accra, Ghana",
      contact: "030 888 9999",
      email: "sales@volvocenteraccra.com",
    },
  },
  {
    Brand: "Toyota",
    category: "SUV",
    Carname: "Land Cruiser",
    production_year: "2023",
    condition: "New",
    price: "Ghc 650,000",
    mileage: "0",
    reviews: "55",
    description:
      "The Toyota Land Cruiser is a legendary SUV known for its off-road capability and durability. It features a 5.7-liter V8 engine, producing 381 horsepower. The Land Cruiser offers a rugged yet comfortable interior, making it perfect for both adventure and daily driving.",
    specs: {
      engine: "5.7L V8",
      horsepower: "381",
      torque: "401 lb-ft",
      acceleration: "6.7 sec",
      top_speed: "130 mph",
      fuel_economy: "13/18 mpg",
      drive_type: "4WD",
      seating: "8",
      cargo_space: "16.1 cu ft",
      warranty: "3 yr/36,000 mi",
      transmission: "8-speed automatic",
      infotainment_system: "Entune with 9-inch touchscreen",
      safety_features: [
        "Toyota Safety Sense",
        "Blind Spot Monitor",
        "Rear Cross-Traffic Alert",
      ],
      color_options: ["Blizzard Pearl", "Midnight Black", "Magnetic Gray"],
    },
    images: {
      interior_images: {
        dashboard: "url_to_dashboard_image",
        seats: "url_to_seats_image",
      },
      exterior_images: {
        front_view: "url_to_front_view_image",
        rear_view: "url_to_rear_view_image",
      },
    },
    dealer_info: {
      name: "Toyota Center Accra",
      address: "707 Adventure Blvd, Accra, Ghana",
      contact: "030 777 8888",
      email: "sales@toyotacenteraccra.com",
    },
  },
  {
    Brand: "Ford",
    category: "Truck",
    Carname: "F-150 Raptor",
    production_year: "2023",
    condition: "New",
    price: "Ghc 500,000",
    mileage: "0",
    reviews: "60",
    description:
      "The Ford F-150 Raptor is a high-performance off-road truck with a powerful 3.5-liter twin-turbo V6 engine. It produces 450 horsepower and is equipped with advanced off-road features, making it perfect for rugged terrains. The Raptor also offers a comfortable and tech-savvy interior.",
    specs: {
      engine: "3.5L V6",
      horsepower: "450",
      torque: "510 lb-ft",
      acceleration: "5.1 sec",
      top_speed: "107 mph",
      fuel_economy: "15/18 mpg",
      drive_type: "4WD",
      seating: "5",
      cargo_space: "52.8 cu ft",
      warranty: "3 yr/36,000 mi",
      transmission: "10-speed automatic",
      infotainment_system: "SYNC 4 with 12-inch touchscreen",
      safety_features: [
        "Ford Co-Pilot360",
        "Trail Control",
        "Terrain Management System",
      ],
      color_options: ["Oxford White", "Agate Black", "Velocity Blue"],
    },
    images: {
      interior_images: {
        dashboard: "url_to_dashboard_image",
        seats: "url_to_seats_image",
      },
      exterior_images: {
        front_view: "url_to_front_view_image",
        rear_view: "url_to_rear_view_image",
      },
    },
    dealer_info: {
      name: "Ford Center Accra",
      address: "808 Power Drive, Accra, Ghana",
      contact: "030 666 7777",
      email: "sales@fordcenteraccra.com",
    },
  },
];
